import { useState, useEffect, useCallback } from 'react';
import PageHeader from '../../components/common/PageHeader';
import Card from '../../components/common/Card';
import { apiClient } from '../../api/client';
import { ShieldCheck, Database, Search } from 'lucide-react';

export const AuditLogs = () => {
  const [logs, setLogs] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(null);

  const loadLogs = useCallback(async (isMounted = true) => {
    setIsLoading(true);
    setError(null);
    try {
      // GET /api/audit-logs (admin only, enforced by backend)
      // Returns array of:
      //   { log_id, table_name, action, old_value, new_value, changed_by, changed_at,
      //     users: { username } }
      const data = await apiClient.get("/audit-logs");
      if (isMounted) setLogs(data);
    } catch (err) {
      if (isMounted) setError(err.message);
    } finally {
      if (isMounted) setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    let isMounted = true;
    loadLogs(isMounted);
    return () => { isMounted = false; };
  }, [loadLogs]);

  const getActionBadge = (action) => {
    switch (action?.toUpperCase()) {
      case 'INSERT':
        return 'px-2 py-0.5 rounded bg-emerald-100 text-emerald-800 font-bold';
      case 'UPDATE':
        return 'px-2 py-0.5 rounded bg-blue-100 text-blue-800 font-bold';
      case 'DELETE':
        return 'px-2 py-0.5 rounded bg-rose-100 text-rose-800 font-bold';
      default:
        return 'px-2 py-0.5 rounded bg-slate-100 text-slate-800 font-bold';
    }
  };

  const formatJsonValue = (value) => {
    if (!value) return <span className="text-slate-400">NULL</span>;
    try {
      const parsed = typeof value === 'string' ? JSON.parse(value) : value;
      return JSON.stringify(parsed);
    } catch {
      return String(value);
    }
  };

  return (
    <div>
      <PageHeader
        title="Database Audit Logs (audit_logs)"
        description="Immutable system audit trail generated by PostgreSQL AFTER UPDATE / AFTER INSERT triggers. No application-level logging."
        badge={
          <span className="px-2.5 py-0.5 rounded-full text-xs font-bold bg-purple-100 text-purple-800 border border-purple-300">
            Admin Only • DB Trigger Powered
          </span>
        }
      />

      <Card
        title="Automated Audit Trail"
        subtitle="Captures (table_name, action, old_state, new_state, changed_by, timestamp) at the SQL level"
      >
        {isLoading && (
          <div className="py-10 text-center text-sm text-slate-500">
            Loading audit logs…
          </div>
        )}

        {!isLoading && error && (
          <div className="py-10 text-center text-sm text-rose-600">
            Failed to load audit logs: {error}
          </div>
        )}

        {!isLoading && !error && logs.length === 0 && (
          <div className="py-10 text-center text-sm text-slate-500">
            No audit logs recorded yet. Logs are automatically generated by PostgreSQL triggers on UPDATE/INSERT operations.
          </div>
        )}

        {!isLoading && !error && logs.length > 0 && (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm">
              <thead>
                <tr className="border-b border-slate-200 text-xs font-semibold text-slate-500 uppercase bg-slate-50/50">
                  <th className="py-3 px-3">Log ID</th>
                  <th className="py-3 px-3">Timestamp</th>
                  <th className="py-3 px-3">Table</th>
                  <th className="py-3 px-3">Operation</th>
                  <th className="py-3 px-3">Old Value</th>
                  <th className="py-3 px-3">New Value</th>
                  <th className="py-3 px-3">Executed By</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 font-mono text-xs text-slate-700">
                {logs.map((log) => (
                  <tr key={log.log_id}>
                    <td className="py-3 px-3 font-bold text-purple-700">
                      #{log.log_id}
                    </td>
                    <td className="py-3 px-3 text-slate-500">
                      {new Date(log.changed_at).toLocaleString("en-PH", {
                        year: "numeric",
                        month: "short",
                        day: "numeric",
                        hour: "2-digit",
                        minute: "2-digit",
                        second: "2-digit",
                      })}
                    </td>
                    <td className="py-3 px-3 font-semibold text-slate-900">
                      {log.table_name}
                    </td>
                    <td className="py-3 px-3">
                      <span className={getActionBadge(log.action)}>
                        {log.action?.toUpperCase()}
                      </span>
                    </td>
                    <td className="py-3 px-3 text-rose-600 font-medium max-w-xs truncate">
                      {formatJsonValue(log.old_value)}
                    </td>
                    <td className="py-3 px-3 text-emerald-600 font-medium max-w-xs truncate">
                      {formatJsonValue(log.new_value)}
                    </td>
                    <td className="py-3 px-3 font-sans text-slate-900">
                      {log.users?.username ?? `User #${log.changed_by}`}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Card>
    </div>
  );
};

export default AuditLogs;
