import PageHeader from '../../components/common/PageHeader';
import Card from '../../components/common/Card';
import { ShieldCheck, Database, Search } from 'lucide-react';

export const AuditLogs = () => {
  return (
    <div>
      <PageHeader
        title="Database Audit Logs (audit_logs)"
        description="Immutable system audit trail generated by PostgreSQL AFTER UPDATE / AFTER INSERT triggers. No application-level logging."
        badge={
          <span className="px-2.5 py-0.5 rounded-full text-xs font-bold bg-purple-100 text-purple-800 border border-purple-300">
            Admin Only • DB Trigger Powered
          </span>
        }
      />

      <Card
        title="Automated Audit Trail"
        subtitle="Captures (table_name, action, old_state, new_state, changed_by, timestamp) at the SQL level"
      >
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm">
            <thead>
              <tr className="border-b border-slate-200 text-xs font-semibold text-slate-500 uppercase bg-slate-50/50">
                <th className="py-3 px-3">Log ID</th>
                <th className="py-3 px-3">Timestamp</th>
                <th className="py-3 px-3">Table</th>
                <th className="py-3 px-3">Operation</th>
                <th className="py-3 px-3">Old Value</th>
                <th className="py-3 px-3">New Value</th>
                <th className="py-3 px-3">Executed By (Role)</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 font-mono text-xs text-slate-700">
              <tr>
                <td className="py-3 px-3 font-bold text-purple-700">AUD-00192</td>
                <td className="py-3 px-3 text-slate-500">2024-09-22 14:32:01</td>
                <td className="py-3 px-3 font-semibold text-slate-900">branch_stock</td>
                <td className="py-3 px-3">
                  <span className="px-2 py-0.5 rounded bg-blue-100 text-blue-800 font-bold">UPDATE</span>
                </td>
                <td className="py-3 px-3 text-rose-600 font-medium">&#123;"qty": 3, "threshold": 5&#125;</td>
                <td className="py-3 px-3 text-emerald-600 font-medium">&#123;"qty": 2, "threshold": 5&#125;</td>
                <td className="py-3 px-3 font-sans text-slate-900">clerk (Marco Santos)</td>
              </tr>
              <tr className="bg-purple-50/30">
                <td className="py-3 px-3 font-bold text-purple-700">AUD-00193</td>
                <td className="py-3 px-3 text-slate-500">2024-09-22 14:32:01</td>
                <td className="py-3 px-3 font-semibold text-slate-900">restock_requests</td>
                <td className="py-3 px-3">
                  <span className="px-2 py-0.5 rounded bg-emerald-100 text-emerald-800 font-bold">INSERT</span>
                </td>
                <td className="py-3 px-3 text-slate-400">NULL</td>
                <td className="py-3 px-3 text-purple-800 font-medium">&#123;"req_id": "REQ-001", "status": "PENDING"&#125;</td>
                <td className="py-3 px-3 font-sans text-purple-900 font-semibold">[DB TRIGGER: trg_auto_restock]</td>
              </tr>
              <tr>
                <td className="py-3 px-3 font-bold text-purple-700">AUD-00191</td>
                <td className="py-3 px-3 text-slate-500">2024-09-21 16:40:12</td>
                <td className="py-3 px-3 font-semibold text-slate-900">central_warehouse</td>
                <td className="py-3 px-3">
                  <span className="px-2 py-0.5 rounded bg-blue-100 text-blue-800 font-bold">UPDATE</span>
                </td>
                <td className="py-3 px-3 text-rose-600 font-medium">&#123;"stock": 130&#125;</td>
                <td className="py-3 px-3 text-emerald-600 font-medium">&#123;"stock": 120&#125;</td>
                <td className="py-3 px-3 font-sans text-purple-900 font-semibold">[STORED PROC: sp_fulfill]</td>
              </tr>
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
};

export default AuditLogs;
